name: Build for Multiple target

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install libusb
      run: sudo apt-get install -y libusb-1.0-0-dev
    - name: make
      run: make
    - name: move and zip file
      run: |
        mkdir linux
        cp vnproch55x linux/
    - uses: actions/upload-artifact@v3
      with:
        name: linux_build
        path: linux        
        
    - name: test win build
      run: |
        echo "need to build for windows"
        sudo apt-get install -y g++-mingw-w64-i686
        unzip -o libusb_mingw32.zip
        sudo cp usr_i686-w64-mingw32_lib/* /usr/i686-w64-mingw32/lib/
        make clean
        make OS_NAME=cygwin host=i686-w64-mingw32 INCLUDE=-I.
        mkdir win
        cp vnproch55x.exe win/
        cp *.dll win/
    - uses: actions/upload-artifact@v3
      with:
        name: win_build
        path: win        

    - name: build with aarch64-linux-gnu
      run: |
        echo "need to build for arm"
        sudo apt-get install -y g++-aarch64-linux-gnu
        unzip -o libusb_arm64.zip
        sudo cp usr_lib_aarch64-linux-gnu/* /usr/lib/aarch64-linux-gnu/
        make clean
        make CPP=aarch64-linux-gnu-g++ host=aarch64-linux-gnu
        mkdir linux_arm64
        cp vnproch55x linux_arm64/
    - uses: actions/upload-artifact@v3
      with:
        name: linux_arm64_build
        path: linux_arm64        
    

