name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_os_matrix:
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install libusb
      run: sudo apt-get install -y libusb-1.0-0-dev
    - name: make
      run: make
    - if: runner.os == 'Linux'
      name: move and zip file
      run: |
        mkdir linux
        cp vnproch55x linux/
    - if: runner.os == 'Linux'
      uses: actions/upload-artifact@v3
      with:
        name: linux_build
        path: linux        
    - if: runner.os == 'Linux'
      run: |
        echo "need to build for arm"
        sudo apt-get install -y g++-aarch64-linux-gnu
        unzip -o libusb_arm64.zip
        sudo cp usr_lib_aarch64-linux-gnu/* /usr/lib/aarch64-linux-gnu/
        make clean
        make CPP=aarch64-linux-gnu-g++ host=aarch64-linux-gnu
        mkdir linux_arm64
        cp vnproch55x linux_arm64/
    - if: runner.os == 'Linux'
      uses: actions/upload-artifact@v3
      with:
        name: linux_arm64_build
        path: linux_arm64        
