name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_os_matrix:
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install libusb
      run: sudo apt-get install -y libusb-1.0-0-dev
    - name: make
      run: make
    - name: move and zip file
      run: |
        mkdir linux
        cp vnproch55x linux/
    - uses: actions/upload-artifact@v3
      with:
        name: linux_build
        path: linux        
    - if: runner.os == 'Linux'
      run: |
        echo "need to build for arm"
        sudo apt-get install -y g++-aarch64-linux-gnu
        echo 'deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal main restricted universe multiverse' | sudo tee -a /etc/apt/sources.list
        echo 'deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal-updates main restricted universe multiverse' | sudo tee -a /etc/apt/sources.list
        echo 'deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal-security main restricted universe multiverse' | sudo tee -a /etc/apt/sources.list
        sudo dpkg --add-architecture arm64
        sudo apt-get update
        sudo apt-get install -y libusb-1.0-0-dev:arm64
        make CPP=aarch64-linux-gnu-g++ host=aarch64-linux-gnu
        echo "aaa" > test.txt
    - if: runner.os == 'Linux'
      uses: actions/upload-artifact@v3
      with:
        name: linux_aarch_build
        path: test.txt        
