name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Install libusb
      run: sudo apt-get install -y libusb-1.0-0-dev
    - name: make
      run: make
    - name: move and zip file
      run: |
        mkdir linux
        cp vnproch55x linux/
        zip -r linux.zip linux
    - uses: actions/upload-artifact@v3
      with:
        name: linux_build
        path: linux.zip        
